name: 💠 3D Contributions

on:
  schedule:
    - cron: "0 2 * * 0" # At 02:00 on Sunday
  workflow_dispatch: # Or when manually dispatched

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name sllozier
          git config user.email sarah.lozier@gmail.com
          git add -A .
          git commit -m "Update 💠 3D Contributions"
          git push
